version: "3.8"

name: The-Bouncer

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-bouncer
    environment:
      # SERVER CONFIG
      PORT: ${PORT}

      # DATABASE CONFIG
      JDBC_URL: ${JDBC_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MAX_DB_POOL_SIZE: ${MAX_DB_POOL_SIZE}
      DB_AUTO_COMMIT: ${DB_AUTO_COMMIT}

      # REDIS CONFIG
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}

      # JWT CONFIG
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    ports:
      - "${DOCKER_PORT}:${PORT}"
    networks:
      - bushive_network

networks:
  bushive_network:
    external: true

volumes:
  postgres_data:
