ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [com.trackmybus.theBouncer.ApplicationKt.module]
  }

  server {
    isProd = false
  }
}

postgres {
  driverClass = "org.postgresql.Driver"
  jdbcURL = "jdbc:postgresql://localhost:5432"
  jdbcURL = ${?JDBC_URL}
  database = "TrackMyBus"
  database = ${?DB_NAME}
  user = "postgres"
  user = ${?DB_USER}
  password = "postgres"
  password = ${?DB_PASSWORD}
  maxPoolSize = 50
  maxPoolSize = ${?MAX_DB_POOL_SIZE}
  autoCommit = true
  autoCommit = ${?DB_AUTO_COMMIT}
}

redis {
  host = "localhost"
  host = ${?REDIS_HOST}
  port = 6379
  port = ${?REDIS_PORT}
  password = "password"
  password = ${?REDIS_PASSWORD}
  database = 0
  database = ${?REDIS_DB}
}
