
name: Check & deploy API documentation
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
jobs:
  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: 70fd74f4-949c-4aba-b1fe-05574d83e8ba
          token: ${{ secrets.BUMP_TOKEN }}
          file: src/main/resources/openapi/documentation.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


